CodeSystem2022/PowerBits-3erSemestre

JavaScript/Semana 4 (24-04 al 08-04)/01-04-Objetos.js
Agregar métodos al constructor del objeto
=> Semana 5 - Video 5.3

JavaScript/Semana 4 (24-04 al 08-04)/01-04-Objetos.js
Distintas formas de crear objetos
=> Semana 5 - Video 5.4

JavaScript/Semana 4 (24-04 al 08-04)/01-04-Objetos.js
=> Semana 5- Video 5.5

Python/Semana 4 (24-04 al 28-04)/Leccion04/BD/prueba_bd.py
=> Semana 5- Video 5.1

JavaScript/Semana 4 (24-04 al 08-04)/01-04-Objetos.js
=> Semana 5 - Video 5.6

Python/Semana 4 (24-04 al 28-04)/Leccion04/BD/prueba_bd.py
=> Semana5 - Video 5.2

.gitignore, Python/Semana 4 (24-04 al 28-04)/Leccion04/BD/v_registros.py
=> Semana 5 - Video 5.3 - Parte2

.gitignore, Java/Semana 6 ( 08-05 al 12-05)/Leccion05/ConversionObjetos/nbproject/private/private.properties, Java/Semana 6 ( 08-05 al 12-05)/Leccion05/ConversionObjetos/src/Test/TestConversionObjetos.java, Java/Semana 6 ( 08-05 al 12-05)/Leccion05/ConversionObjetos/src/domain/Empleado.java, Java/Semana 6 ( 08-05 al 12-05)/Leccion05/ConversionObjetos/src/domain/Escritor.java
Pruebas con Downcasting y Upcasting: Parte 2
=> Semana 5 - Video 5.2

Python/Semana 4 (24-04 al 28-04)/Leccion04/BD/v_i_registros.py
=> Semana 5 - Video 5.5

JavaScript/Semana 4 (24-04 al 08-04)/01-04-Objetos.js
=> Semana5 - Video 5.7

Python/Semana 4 (24-04 al 28-04)/Leccion04/BD/actualizar_registro.py, Python/Semana 4 (24-04 al 28-04)/Leccion04/BD/v_registros.py
Actualizar o modificar un registro
=> Semana 5- Video 5.6

Python/Semana 4 (24-04 al 28-04)/Leccion04/BD/actualizar_varios_reg.py
Actualizar o modificar varios registros.
=> Semana 5 - Video 5.7

JavaScript/Semana 7 (19-05 al 26-05)/05-03-clases.js
Sintaxis de Clases en JavaScript: (Parte 2)
=> Semana 7 - Video 6.1(Parte 2)

JavaScript/Semana 7 (19-05 al 26-05)/05-03-clases.js
Metodo Get y Set: Parte Get y Parte Set (Video 4)
=> Semana 7 - Video 6.2 Parte 2

Python/Semana 8 (22-05 al 26-05)/Leccion07/base_datos.uxf
=> Clase 8 - Video 7.1

JavaScript/Semana 7 (19-05 al 26-05)/05-03-clases.js, JavaScript/Semana 7 (19-05 al 26-05)/index.html
=> Semana 8 - Video 7.2

Python/Semana 8 (22-05 al 26-05)/Leccion07/capa_datos_persona/logger_base.py
=> Clase 7 - Video 7.2 Parte 1

Java/Semana 6 ( 08-05 al 12-05)/Leccion05/ClasesAbstractas/nbproject/private/private.properties, Java/Semana 8 (22-05 al 26-05)/Leccion06/Interfaces/src/accesodatos/ImplementacionMySql.java
Manejo de interfaces (Parte 3)
=> Clase 7 - Video 7.3

Java/Semana 8 (22-05 al 26-05)/Leccion06/Interfaces/src/accesodatos/ImplementacionOracle.java
=> Clase 7- Video 7.4

.gitignore, Java/Semana 8 (22-05 al 26-05)/Leccion06/Interfaces/src/test/TestInterfaces.java
=> Clase 7 - Video 7.5 (Parte 2)

Python/Semana 8 (22-05 al 26-05)/Leccion07/capa_datos_persona/Persona.py
=> Clase 8 - Video 8.1

JavaScript/Semana 7 (19-05 al 26-05)/05-03-clases.js
=> Clase 8 - Video 8.2

Java/Semana 9 (29-05 al 02-06)/Leccion08/ManejoExcepciones1/src/test/TestExcepciones.java
Comenzamos Con Excepciones: Parte 2, 3, 4.
=> Clase 8 - Video 8.3 Parte (2,3,4)

Python/Semana 8 (22-05 al 26-05)/Leccion07/capa_datos_persona/conexion.py
Creación de la Clase Conexión: Parte 1
=> Clase 8 - Video 8.3 (Parte 1)

Python/Semana 8 (22-05 al 26-05)/Leccion07/capa_datos_persona/conexion.py
Creación de la Clase Conexión: Parte 2
=> Clase 8 - Video 8.3 (Parte 2)

JavaScript/Semana 7 (19-05 al 26-05)/05-03-clases.js
=> Clase 8 - Video 8.4 Parte2

JavaScript/Semana 7 (19-05 al 26-05)/05-03-clases.js
Creación de constantes estáticas.
=> Clase 8 - Video 8.5

Python/Semana 8 (22-05 al 26-05)/Leccion07/capa_datos_persona/persona_dao.py
En la clase PersonaDao: método seleccionar
=> Clase 9 - Video 9.1

Python/Semana 8 (22-05 al 26-05)/Leccion07/capa_datos_persona/persona_dao.py
=> Clase 9 - Video 9.2

Python/Semana 8 (22-05 al 26-05)/Leccion07/capa_datos_persona/persona_dao.py
=> Clase 9 - Video 9.4

Python/Semana 8 (22-05 al 26-05)/Leccion07/capa_datos_persona/Persona.py, Python/Semana 8 (22-05 al 26-05)/Leccion07/capa_datos_persona/persona_dao.py
=> Clase 9 - Video 9.5

JavaScript/Semana 10 (05-06 al 09-06)/PruebaPersonas.js
=> Clase 9 - Video 9.6

JavaScript/Semana 10 (05-06 al 09-06)/PruebaPersonas.js
=> Clase 9 - Video 9.7

Java/Semana 10 (04-06 al 09-06)/Leccion09/CalculadoraUTN/CalculadoraUTN.java
Factorizamos el código a través del método mostrarMenu
=> Clase 9 - Video 9.8

Java/Semana 10 (04-06 al 09-06)/Leccion09/CalculadoraUTN/CalculadoraUTN.java
Función ejecutarOperacion y pruebas
=> Clase 9 - Video 9.9

JavaScript/Semana 11 (12-06 al 16-06)/diagrama_de_ventas.uxf
Introducción al sistema de ventas
=> Clase 10 - Video 10.1

Python/Semana 8 (22-05 al 26-05)/Leccion07/capa_datos_persona/conexion.py
Obtener una conexión a partir de Pool (Video 1).
=> Clase 10 - Video 10.2

JavaScript/Semana 11 (12-06 al 16-06)/SistemaVentas.js
=> Clase 10 - Video 10.3

JavaScript/Semana 11 (12-06 al 16-06)/SistemaVentas.js
Pruebas con la relación de Agregación.
=> Clase 10 - Video 10.5 parte 1

Java/Semana 11 (12-06 al 16-06)/Leccion11/ListarPersonas/src/Persona.java
=> Clase 10 - Video 10.2 (Parte 3)

Java/Semana 11 (12-06 al 16-06)/Leccion11/Leccion11.iml, Java/Semana 11 (12-06 al 16-06)/Leccion11/ListarPersonas/src/ListadoPersonasApp.java, Java/Semana 11 (12-06 al 16-06)/Leccion11/ListarPersonas/src/Main.java
=> Clase 10 - Video 10.3 (Parte 1)

Java/Semana 11 (12-06 al 16-06)/Leccion11/ListarPersonas/src/ListadoPersonasApp.java
Agregamos el try catch y el método ejecutarOperación(). También incorporamos lambda y el método por referencia.
=> Clase 10 - Video 10.4 (Parte 1 y 2)

Python/Semana 8 (22-05 al 26-05)/Leccion07/capa_datos_persona/cursor_del_pool.py
Creamos la Clase CursorDelPool -> Parte 1
=> Clase 11 - Video 11.3

Java/Semana 12 (26-06 al 03-07)/SistemaEstudiantes/src/main/java/UTN/conexion/Conexion.java
Creamos la clase conexión (Parte 1)
=> Clase 11 - Video 11.4

Java/Semana 12 (26-06 al 03-07)/SistemaEstudiantes/src/main/java/UTN/datos/EstudianteDAO.java
Listado de estudiantes, con la clase EstudianteDAO. (Parte 1)
=> Clase 12 - Video 12.2.1

Java/Semana 12 (26-06 al 03-07)/SistemaEstudiantes/src/main/java/UTN/datos/EstudianteDAO.java
Listado de estudiantes con la Clase EstudianteDAO -> Parte 3
=> Clase 12 - Video 12.2 (Parte 3)

Java/Semana 12 (26-06 al 03-07)/SistemaEstudiantes/src/main/java/UTN/datos/EstudianteDAO.java
Método eliminar estudiante y prueba (Parte1)
=> Clase 01 Aplicación Sistema Estudiantes Parte 3: Video 1.1
